// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_rpg.Data;

#nullable disable

namespace dotnetrpg.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotnet_rpg.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseArmor")
                        .HasColumnType("int");

                    b.Property<int>("BaseResistance")
                        .HasColumnType("int");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("CurrentEnergy")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("int");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<int?>("FightId")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("InventorySize")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayerCharacter")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spirit")
                        .HasColumnType("int");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FightId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("dotnet_rpg.Models.Fight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("dotnet_rpg.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("Spirit")
                        .HasColumnType("int");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Item");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("dotnet_rpg.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseDamageAttributeScalingFactor")
                        .HasColumnType("int");

                    b.Property<int>("CharacterClass")
                        .HasColumnType("int");

                    b.Property<int>("Cooldown")
                        .HasColumnType("int");

                    b.Property<int>("DamageType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnergyCost")
                        .HasColumnType("int");

                    b.Property<int>("Healing")
                        .HasColumnType("int");

                    b.Property<int>("MaxBaseDamageFactor")
                        .HasColumnType("int");

                    b.Property<int>("MinBaseDamageFactor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<int>("WeaponDamagePercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDamageAttributeScalingFactor = 90,
                            CharacterClass = 1,
                            Cooldown = 5,
                            DamageType = 1,
                            Description = "Violently charge the enemy.",
                            EnergyCost = 15,
                            Healing = 0,
                            MaxBaseDamageFactor = 40,
                            MinBaseDamageFactor = 30,
                            Name = "Charge",
                            Rank = 1,
                            TargetType = 3,
                            WeaponDamagePercentage = 10
                        },
                        new
                        {
                            Id = 2,
                            BaseDamageAttributeScalingFactor = 90,
                            CharacterClass = 1,
                            Cooldown = 5,
                            DamageType = 1,
                            Description = "Violently charge the enemy.",
                            EnergyCost = 15,
                            Healing = 0,
                            MaxBaseDamageFactor = 50,
                            MinBaseDamageFactor = 40,
                            Name = "Charge",
                            Rank = 2,
                            TargetType = 3,
                            WeaponDamagePercentage = 20
                        },
                        new
                        {
                            Id = 3,
                            BaseDamageAttributeScalingFactor = 90,
                            CharacterClass = 1,
                            Cooldown = 5,
                            DamageType = 1,
                            Description = "Violently charge the enemy.",
                            EnergyCost = 15,
                            Healing = 0,
                            MaxBaseDamageFactor = 50,
                            MinBaseDamageFactor = 40,
                            Name = "Charge",
                            Rank = 3,
                            TargetType = 3,
                            WeaponDamagePercentage = 30
                        });
                });

            modelBuilder.Entity("dotnet_rpg.Models.SkillInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingCooldown")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillInstance");
                });

            modelBuilder.Entity("dotnet_rpg.Models.StatusEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DamagePerTurn")
                        .HasColumnType("int");

                    b.Property<int>("DecreasedDamagePercentage")
                        .HasColumnType("int");

                    b.Property<int>("DecreasedDamageTakenPercentage")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("HealingPerTurn")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedArmorPercentage")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedDamagePercentage")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedDamageTakenPercentage")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedIntelligencePercentage")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedResistancePercentage")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedStrengthPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsStunned")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReducedArmorPercentage")
                        .HasColumnType("int");

                    b.Property<int>("ReducedIntelligencePercentage")
                        .HasColumnType("int");

                    b.Property<int>("ReducedResistancePercentage")
                        .HasColumnType("int");

                    b.Property<int>("ReducedStrengthPercentage")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId")
                        .IsUnique();

                    b.ToTable("StatusEffect");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DamagePerTurn = 0,
                            DecreasedDamagePercentage = 0,
                            DecreasedDamageTakenPercentage = 0,
                            Duration = 1,
                            HealingPerTurn = 0,
                            IncreasedArmorPercentage = 0,
                            IncreasedDamagePercentage = 0,
                            IncreasedDamageTakenPercentage = 0,
                            IncreasedIntelligencePercentage = 0,
                            IncreasedResistancePercentage = 0,
                            IncreasedStrengthPercentage = 0,
                            IsStunned = true,
                            Name = "Charge Stun",
                            ReducedArmorPercentage = 0,
                            ReducedIntelligencePercentage = 0,
                            ReducedResistancePercentage = 0,
                            ReducedStrengthPercentage = 0,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            DamagePerTurn = 0,
                            DecreasedDamagePercentage = 0,
                            DecreasedDamageTakenPercentage = 0,
                            Duration = 1,
                            HealingPerTurn = 0,
                            IncreasedArmorPercentage = 0,
                            IncreasedDamagePercentage = 0,
                            IncreasedDamageTakenPercentage = 0,
                            IncreasedIntelligencePercentage = 0,
                            IncreasedResistancePercentage = 0,
                            IncreasedStrengthPercentage = 0,
                            IsStunned = true,
                            Name = "Charge Stun",
                            ReducedArmorPercentage = 0,
                            ReducedIntelligencePercentage = 0,
                            ReducedResistancePercentage = 0,
                            ReducedStrengthPercentage = 0,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 3,
                            DamagePerTurn = 0,
                            DecreasedDamagePercentage = 0,
                            DecreasedDamageTakenPercentage = 0,
                            Duration = 1,
                            HealingPerTurn = 0,
                            IncreasedArmorPercentage = 0,
                            IncreasedDamagePercentage = 0,
                            IncreasedDamageTakenPercentage = 0,
                            IncreasedIntelligencePercentage = 0,
                            IncreasedResistancePercentage = 0,
                            IncreasedStrengthPercentage = 0,
                            IsStunned = true,
                            Name = "Charge Stun",
                            ReducedArmorPercentage = 0,
                            ReducedIntelligencePercentage = 0,
                            ReducedResistancePercentage = 0,
                            ReducedStrengthPercentage = 0,
                            SkillId = 3
                        });
                });

            modelBuilder.Entity("dotnet_rpg.Models.StatusEffectInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingDuration")
                        .HasColumnType("int");

                    b.Property<int>("StatusEffectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("StatusEffectId");

                    b.ToTable("StatusEffectInstance");
                });

            modelBuilder.Entity("dotnet_rpg.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dotnet_rpg.Models.ArmorPiece", b =>
                {
                    b.HasBaseType("dotnet_rpg.Models.Item");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Resistance")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("dotnet_rpg.Models.Weapon", b =>
                {
                    b.HasBaseType("dotnet_rpg.Models.Item");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("int");

                    b.Property<int>("MinDamage")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("dotnet_rpg.Models.Character", b =>
                {
                    b.HasOne("dotnet_rpg.Models.Fight", "Fight")
                        .WithMany("Characters")
                        .HasForeignKey("FightId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("dotnet_rpg.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId");

                    b.Navigation("Fight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dotnet_rpg.Models.Item", b =>
                {
                    b.HasOne("dotnet_rpg.Models.Character", null)
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("dotnet_rpg.Models.SkillInstance", b =>
                {
                    b.HasOne("dotnet_rpg.Models.Character", "Character")
                        .WithMany("SkillInstances")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_rpg.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("dotnet_rpg.Models.StatusEffect", b =>
                {
                    b.HasOne("dotnet_rpg.Models.Skill", "Skill")
                        .WithOne("StatusEffect")
                        .HasForeignKey("dotnet_rpg.Models.StatusEffect", "SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("dotnet_rpg.Models.StatusEffectInstance", b =>
                {
                    b.HasOne("dotnet_rpg.Models.Character", "Character")
                        .WithMany("StatusEffectInstances")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_rpg.Models.StatusEffect", "StatusEffect")
                        .WithMany("StatusEffectInstances")
                        .HasForeignKey("StatusEffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("StatusEffect");
                });

            modelBuilder.Entity("dotnet_rpg.Models.Character", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("SkillInstances");

                    b.Navigation("StatusEffectInstances");
                });

            modelBuilder.Entity("dotnet_rpg.Models.Fight", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("dotnet_rpg.Models.Skill", b =>
                {
                    b.Navigation("StatusEffect");
                });

            modelBuilder.Entity("dotnet_rpg.Models.StatusEffect", b =>
                {
                    b.Navigation("StatusEffectInstances");
                });

            modelBuilder.Entity("dotnet_rpg.Models.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
